name: 'minecraft changelog scraping'

on:
    workflow_dispatch:
    # schedule to run every day at 12:00
    schedule:
        - cron: '0 15,3 * * *' # JSTの0時（UTCの前日15時） JSTの12時（UTCの3時）

jobs:
    run:
        runs-on: ubuntu-latest
        env:
            DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
            GLOSSARY_ID: ${{ vars.GLOSSARY_ID }}
            SCRAPING_LOG: ${{ vars.SCRAPING_LOG }}
        steps:
            # Checkout the repository
            - name: 'Checkout'
              uses: actions/checkout@v4

            # Setup Python
            - name: 'Setup Python'
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.8'

            # cache the virtual environment
            - name: Cache virtual environment
              id: cache-venv
              uses: actions/cache@v4
              with:
                  path: .venv
                  key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

            # Install dependencies
            - name: Set up virtual environment
              if: steps.cache-venv.outputs.cache-hit != 'true'
              run: |
                  python -m venv .venv
                  source .venv/bin/activate
                  pip install -r requirements.txt
                  deactivate

            # activate the virtual environment and check
            - name: Activate virtual environment
              run: |
                  source .venv/bin/activate
                  which python
                  pip list
                  deactivate

            # run scraping.py
            - name: Run scraping.py
              run: |
                  source .venv/bin/activate
                  python scraping.py
                  deactivate

            # set vars.SCRAPING_LOG
            - name: Set vars.SCRAPING_LOG
              if: ${{ hashFiles('scraping.log') != ''  }}
              run: |
                  gh variable set SCRAPING_LOG --body "$(cat scraping.log)"
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              continue-on-error: true
