name: 'minecraft changelog scraping'

on:
    workflow_dispatch:
    # schedule to run every day at 12:00 UTC
    # schedule:
    #     - cron: '0 12 * * *'

jobs:
    run:
        runs-on: ubuntu-latest
        env:
            DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        steps:
            # Checkout the repository
            - name: 'Checkout'
              uses: actions/checkout@v4

            # Setup Python
            - name: 'Setup Python'
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.8'

            # cache the virtual environment
            - name: Cache virtual environment
              id: cache-venv
              uses: actions/cache@v4
              with:
                  path: .venv
                  key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

            # Install dependencies
            - name: Set up virtual environment
              if: steps.cache-venv.outputs.cache-hit != 'true'
              run: |
                  python -m venv .venv
                  source .venv/bin/activate
                  pip install -r requirements.txt
                  deactivate

            # activate the virtual environment and check
            - name: Activate virtual environment
              run: |
                  source .venv/bin/activate
                  which python
                  pip list
                  deactivate

            - name: Check
              run: |
                  ls -al

            # download scraping.log from actions artifact
            - name: Download scraping.log
              uses: actions/download-artifact@v4
              with:
                  name: scraping_log
              continue-on-error: true

            # run scraping.py
            - name: Run scraping.py
              run: |
                  source .venv/bin/activate
                  python scraping.py
                  deactivate

            # upload scraping.log to actions artifact
            - name: Upload scraping.log
              uses: actions/upload-artifact@v4
              with:
                  name: scraping_log
                  path: scraping.log
