name: 'minecraft changelog scraping'

on:
    workflow_dispatch:
    # schedule to run every day at 12:00
    schedule:
        - cron: '0 12 * * *'
        - cron: '0 0 * * *'

jobs:
    run:
        runs-on: ubuntu-latest
        env:
            DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        steps:
            # Checkout the repository
            - name: 'Checkout'
              uses: actions/checkout@v4

            # Setup Python
            - name: 'Setup Python'
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.8'

            # cache the virtual environment
            - name: Cache virtual environment
              id: cache-venv
              uses: actions/cache@v4
              with:
                  path: .venv
                  key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

            # Install dependencies
            - name: Set up virtual environment
              if: steps.cache-venv.outputs.cache-hit != 'true'
              run: |
                  python -m venv .venv
                  source .venv/bin/activate
                  pip install -r requirements.txt
                  deactivate

            # activate the virtual environment and check
            - name: Activate virtual environment
              run: |
                  source .venv/bin/activate
                  which python
                  pip list
                  deactivate

            - name: create id
              id: log-id
              run: echo "id=$(date +%s)" >> $GITHUB_OUTPUT

            # get glossary_id.txt from actions cache
            - name: Cache glossary_id.txt
              id: cache-glossary-id
              uses: actions/cache@v4
              with:
                  path: glossary_id.txt
                  key: ${{ runner.os }}-glossary-id-${{ hashFiles('glossary.csv') }}
                  restore-keys: |
                      ${{ runner.os }}-glossary-id-

            # get scraping.log from actions cache
            - name: Cache scraping.log
              id: cache-scraping-log
              uses: actions/cache@v4
              with:
                  path: scraping.log
                  key: ${{ runner.os }}-scraping-log-${{ steps.log-id.outputs.id }}
                  restore-keys: |
                      ${{ runner.os }}-scraping-log-

            # run scraping.py
            - name: Run scraping.py
              run: |
                  source .venv/bin/activate
                  python scraping.py
                  deactivate
